backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/img/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Category", name: "category", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Facebook Title", name: "fb_title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "select", options: ["Rappresentanza/Elezioni Studentesche","Associazione","Rappresentanza","Senato Accademico","Meritocrazia","Partecipazione e Servizi agli Studenti","Internazionalizzazione","Consiglio degli Studenti","Budget","Architettura Urbanistica e Ingegneria delle Costruzioni","Prove in itinere e programmazione Didattica","Consiglio di Amministrazione","Diritto allo Studio","calendario accademico prove in itinere e programmazione didattica","Residenze","Internazionalizzazione e Mobilità","Progetto Piano ViVi.Polimi e Spazi Studio","Progetto Piano","ViVi.Polimi e spazi studio","Elezioni studentesche","Calendario accademico Prove in Itinire e Programmazione Didattica","Architettura urbanistica ed ing. costru.","Consiglio Nazionale degli Studenti Universitari","Diritto allo Studio Universitario","Architettura Urbanistica ed Ingegneria delle Costruzioni","Ingegneria Industriale e dell'Informazione","Rappresentanza/Calendario","prove itinere e programmazione","Rappresentanza/Internazionalizzazione","Architettura Urbanistica Ing. delle Costruzioni","Rappresentanza/Calendario Accademico","prove in itinere e programmazione didattiva","Rappresentanza/Diritto allo studio","Calendario accademico"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image (unsplash id)", name: "image", widget: "string", default: "bj3l739cwc8"}
      - {label: "Body", name: "body", widget: "markdown"}
collections:
  - name: "faq" # Used in routes, e.g., /admin/collections/blog
    label: "FAQ" # Used in the UI
    folder: "_posts/faq" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "faq"}
      - {label: "Category", name: "category", widget: "hidden", default: "faq"}
      - {label: "Question", name: "title", widget: "string"}
      - {label: "Answer", name: "body", widget: "markdown"}
      - {label: "Link", name: "link", widget: "markdown"}
