backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"
collections:
  - name: "blog-it" # Used in routes, e.g., /admin/collections/blog
    label: "Blog (it)" # Used in the UI
    folder: "_posts/blog/it" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "it"}
      - {label: "Amp", name: "isAmp", widget: "hidden", default: "true"}
      - {label: "Titolo (max 66 caratteri)", name: "title", widget: "string"}
      - {label: "Categoria", name: "tags", widget: "select", options: ["Architettura Urbanistica Ingegneria delle Costruzioni", "Associazione", "Consiglio degli Studenti", "Consiglio di Amministrazione", "Consiglio Nazionale degli Studenti Universitari", "Design", "Ingegneria Civile, Ambientale e Territoriale", "Ingegneria Industriale e dell’Informazione", "Rappresentanza", "Senato Accademico"], multiple: false}
      - {label: "Riassunto (max 200 caratteri)", name: "desc", widget: "text" }
      - {label: "Testo", name: "body", widget: "markdown"}
      - {label: "Articolo in Inglese", name: "translations.en", widget: "relation", required: false, collection: "blog-en", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Miniatura Articolo", name: "th", widget: "image", required: true}
      - {label: "Correlati (max 4)", name: "related", widget: "relation", multiple: true, required: false, collection: "blog-it", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Referenti", name: "authors", widget: "relation", multiple: true, required: true, collection: "users-it", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Pubblicato", name: "published", widget: "boolean", default: false}
      - {label: "Data di Pubblicazione (la programmazione NON e' supportata)", name: "date", widget: "datetime"}
  - name: "blog-en" # Used in routes, e.g., /admin/collections/blog
    label: "Blog (en)" # Used in the UI
    folder: "_posts/blog/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "en"}
      - {label: "Amp", name: "isAmp", widget: "hidden", default: "true"}
      - {label: "Titolo (max 66 caratteri)", name: "title", widget: "string"}
      - {label: "Categoria", name: "tags", widget: "select", options: ["Architettura Urbanistica Ingegneria delle Costruzioni", "Associazione", "Consiglio degli Studenti", "Consiglio di Amministrazione", "Consiglio Nazionale degli Studenti Universitari", "Design", "Ingegneria Civile, Ambientale e Territoriale", "Ingegneria Industriale e dell’Informazione", "Rappresentanza", "Senato Accademico"], multiple: false}
      - {label: "Riassunto (max 200 caratteri)", name: "desc", widget: "text" }
      - {label: "Testo", name: "body", widget: "markdown"}
      - {label: "Articolo in Inglese", name: "translations.it", widget: "relation", required: false, collection: "blog-it", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Miniatura Articolo", name: "th", widget: "image", required: true}
      - {label: "Correlati (max 4)", name: "related", widget: "relation", multiple: true, required: false, collection: "blog-en", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Referenti", name: "authors", widget: "relation", multiple: true, required: true, collection: "users-en", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Pubblicato", name: "published", widget: "boolean", default: false}
      - {label: "Data di Pubblicazione (la programmazione NON e' supportata)", name: "date", widget: "datetime"}
  - name: "users-it" # Used in routes, e.g., /admin/collections/blog
    label: "Utenti (it)" # Used in the UI
    folder: "_posts/users/it" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "users"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "it"}
      - {label: "Amp", name: "isAmp", widget: "hidden", default: "true"}
      - {label: "Nome e Cognome", name: "title", widget: "string"}
      - {label: "Bio", name: "body", widget: "markdown" }
      - {label: "Utente in Inglese", name: "translations.en", widget: "relation", required: false, collection: "users-en", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Immagine", name: "th", widget: "image", required: true}
      - label: "Profili"
        name: "socials"
        widget: "object"
        fields:
          - {label: "Facebook Id", name: "fb", widget: "string", required: false}
          - {label: "Telegram Id", name: "tg", widget: "string", required: false}
          - {label: "Svolta Id", name: "mail", widget: "string"}
      - {label: "Pubblicato", name: "published", widget: "boolean", default: false}
      - {label: "Data di Pubblicazione (la programmazione NON e' supportata)", name: "date", widget: "datetime"}
  - name: "users-en" # Used in routes, e.g., /admin/collections/blog
    label: "Utenti (en)" # Used in the UI
    folder: "_posts/users/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "users"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "en"}
      - {label: "Amp", name: "isAmp", widget: "hidden", default: "true"}
      - {label: "Nome e Cognome", name: "title", widget: "string"}
      - {label: "Bio", name: "body", widget: "markdown" }
      - {label: "Utente in Italiano", name: "translations.it", widget: "relation", required: false, collection: "users-it", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Immagine", name: "th", widget: "image", required: true}
      - label: "Profili"
        name: "socials"
        widget: "object"
        fields:
          - {label: "Facebook Id", name: "fb", widget: "string", required: false}
          - {label: "Telegram Id", name: "tg", widget: "string", required: false}
          - {label: "Svolta Id", name: "mail", widget: "string"}
      - {label: "Pubblicato", name: "published", widget: "boolean", default: false}
      - {label: "Data di Pubblicazione (la programmazione NON e' supportata)", name: "date", widget: "datetime"}
  - name: "events-it" # Used in routes, e.g., /admin/collections/blog
    label: "Eventi (it)" # Used in the UI
    folder: "_posts/events/it" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "events"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "it"}
      - {label: "Amp", name: "isAmp", widget: "hidden", default: "true"}
      - {label: "Titolo (max 66 caratteri)", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "tags", widget: "select", options: ["Viaggio", "Attivita'", "Conferenza", "Workshop", "Evento"], multiple: false}
      - {label: "Descrizione", name: "body", widget: "markdown" }
      - {label: "Evento in Inglese", name: "translations.en", widget: "relation", required: false, collection: "events-it", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Copertina", name: "th", widget: "image", required: true}
      - {label: "Pubblicato", name: "published", widget: "boolean", default: false}
      - label: "Descrizione"
        name: "days"
        widget: "object"
        fields:
          - {label: "Giorno 1", name: "day1", widget: "markdown" }
          - {label: "Giorno 2", name: "day2", widget: "markdown" }
          - {label: "Giorno 3", name: "day3", widget: "markdown" }
          - {label: "Giorno 4", name: "day4", widget: "markdown" }
          - {label: "Giorno 5", name: "day5", widget: "markdown" }
      - {label: "Prezzo", name: "price", widget: "number", type: "float", min: 0, step: 0.01}
  - name: "events-en" # Used in routes, e.g., /admin/collections/blog
    label: "Blog (en)" # Used in the UI
    folder: "_posts/blog/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "en"}
      - {label: "Amp", name: "isAmp", widget: "hidden", default: "true"}
      - {label: "Titolo (max 66 caratteri)", name: "title", widget: "string"}
      - {label: "Categoria", name: "tags", widget: "select", options: ["Architettura Urbanistica Ingegneria delle Costruzioni", "Associazione", "Consiglio degli Studenti", "Consiglio di Amministrazione", "Consiglio Nazionale degli Studenti Universitari", "Design", "Ingegneria Civile, Ambientale e Territoriale", "Ingegneria Industriale e dell’Informazione", "Rappresentanza", "Senato Accademico"], multiple: false}
      - {label: "Riassunto (max 200 caratteri)", name: "desc", widget: "text" }
      - {label: "Testo", name: "body", widget: "markdown"}
      - {label: "Articolo in Inglese", name: "translations.it", widget: "relation", required: false, collection: "blog-it", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Miniatura Articolo", name: "th", widget: "image", required: true}
      - {label: "Correlati (max 4)", name: "related", widget: "relation", multiple: true, required: false, collection: "blog-en", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Referenti", name: "authors", widget: "relation", multiple: true, required: true, collection: "users-en", searchFields: ["title"], displayFields: ["title"], valueField: "title"}
      - {label: "Pubblicato", name: "published", widget: "boolean", default: false}
      - {label: "Data di Pubblicazione (la programmazione NON e' supportata)", name: "date", widget: "datetime"}
