backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
media_folder: "assets/img/uploads"
public_folder: "/assets/files/uploads"
collections:
  - name: "blog-it" # Used in routes, e.g., /admin/collections/blog
    label: "Blog (it)" # Used in the UI
    folder: "_posts/blog/it" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "it"}
      - {label: "Data di Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Pubblicato", name: "published", widget: "boolean", default: "false"}
      - {label: "Titolo (max 100 caratteri)", name: "title", widget: "string"}
      - label: "Info"
        name: "info"
        widget: "object"
        fields:
          - {label: "Tags", name: "tags", widget: "select", options: ["Architettura Urbanistica Ingegneria delle Costruzioni", "Associazione", "Consiglio degli Studenti", "Consiglio di Amministrazione", "Consiglio Nazionale degli Studenti Universitari", "Design", "Ingegneria Civile, Ambientale e Territoriale", "Ingegneria Industriale e dell’Informazione", "Rappresentanza", "Senato Accademico"], multiple: true}
          - {label: "Autore", name: "author", widget: "string" }
      - label: "Traduzioni"
        name: "translations"
        widget: "object"
        fields:
          - {label: "Traduzione Italiana", name: "it", widget: "hidden", default: "-"}
          - {label: "Traduzione Inglese", name: "en", widget: "relation", required: false, collection: "blog-en", searchFields: ["title"], displayFields: "title", valueField: "title"}
      - label: "Immagini"
        name: "images"
        widget: "object"
        fields:
          - {label: "Copertina Sito", name: "th", widget: "image", default: "", required: false}
          - {label: "Social", name: "social", widget: "image", default: "", required: false}
          - {label: "Ricerca 1:1 (Min 1200px Wide)", name: "amp_1-1", widget: "image", default: "", required: false}
          - {label: "Ricerca 4:3 (Min 1200px Wide)", name: "amp_4-3", widget: "image", default: "", required: false}
          - {label: "Ricerca 16:9 (Min 1200px Wide)", name: "amp_16-9", widget: "image", default: "", required: false}
      - {label: "Testo", name: "body", widget: "markdown"}
  - name: "blog-en" # Used in routes, e.g., /admin/collections/blog
    label: "Blog (en)" # Used in the UI
    folder: "_posts/blog/en" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Published", name: "published", widget: "boolean", default: "false"}
      - {label: "Lingua", name: "category", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "select", options: ["Architettura Urbanistica Ingegneria delle Costruzioni", "Associazione", "Consiglio degli Studenti", "Consiglio di Amministrazione", "Consiglio Nazionale degli Studenti Universitari", "Design", "Ingegneria Civile, Ambientale e Territoriale", "Ingegneria Industriale e dell’Informazione", "Rappresentanza", "Senato Accademico"], multiple: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Authors", name: "authors", widget: "string"}
      - {label: "Image", name: "image", widget: "image", default: "", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Traduzione Inglese", name: "link_en", widget: "hidden", default: "-"}
      - {label: "Traduzione Italiana", name: "link_it", widget: "relation", required: false, collection: "blog-it", searchFields: ["title"], valueField: "title", displayFields: "title"}
  - name: "events" # Used in routes, e.g., /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "_posts/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "events"}
      - {label: "Category", name: "category", widget: "hidden", default: "events"}
      - {label: "Pretix ID", name: "pretix_id", widget: "string"}
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "See Also", name: "related", widget: "relation", required: false, collection: "events", searchFields: "fields.title", valueField: "slug", multiple: true}
      - {label: "Descrizione", name: "body", widget: "markdown"}
      - {label: "Prezzo", name: "price", widget: "number"}
      - {label: "Iniziativa realizzata con il contributo del Politecnico di Milano", name: "contributo_poli", widget: "boolean", default: true}
